#!/bin/sh

PACKAGE_NAME=thinkpad-wmi-dkms

VERSION=`dpkg-query -W -f='${Version}' $PACKAGE_NAME | awk -F "-" '{print $1}' \
    | cut -d\: -f2`

set -e

case "$1" in
    remove|upgrade|deconfigure)
      if [  "`dkms status -m \"$PACKAGE_NAME\"`" ]; then
         dkms remove -m "$PACKAGE_NAME" -v "$VERSION" --all
      fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#
